import type { IconType } from "react-icons";
import {
  FaWifi,
  FaTv,
  FaFan,
  FaGlassWhiskey,
  FaWineGlassAlt,
  FaShower,
  FaLaptop,
  FaBath,
  FaBoxOpen,
  FaBed,
  FaHotTub,
  FaCouch,
  FaLock,
  FaTshirt,
  FaCrown,
  FaConciergeBell,
  FaDoorOpen,
} from "react-icons/fa";

import {
  GiHanger,
  GiVacuumCleaner,
  GiCoffeeCup,
  GiSlippers,
} from "react-icons/gi";

import { IoBedOutline } from "react-icons/io5";

import {
  MdOutlineMeetingRoom,
  MdOutlineLocalDrink,
  MdKitchen,
  MdOutlineFreeBreakfast,
  MdOutlineRoomService,
} from "react-icons/md";

export const AMENITIES: Record<string, IconType> = {
  "Free Wi-Fi": FaWifi,
  "High-speed Wi-Fi": FaWifi,
  "Flat-screen TV": FaTv,
  "Smart TV with Streaming": FaTv,
  "Air Conditioning": FaFan,
  "Mini-bar": FaGlassWhiskey,
  "Fully-stocked Mini-bar": FaWineGlassAlt,
  "Rainfall Shower": FaShower,
  "Work Desk": FaLaptop,
  "Ergonomic Work Desk": FaLaptop,
  Wardrobe: GiHanger,
  "Complimentary Toiletries": FaBath,
  "Luxury Toiletries": FaBath,
  "Daily Housekeeping": GiVacuumCleaner,
  "Coffee/Tea Station": GiCoffeeCup,
  "Coffee Maker": GiCoffeeCup,
  "Nespresso Coffee Machine": GiCoffeeCup,
  "Mini-fridge": FaBoxOpen,
  "Premium Bedding": FaBed,
  "King-size Bed": IoBedOutline,
  "Jacuzzi Bathtub": FaHotTub,
  Bathtub: FaBath,
  "Separate Seating Area": FaCouch,
  "Living Room": FaCouch,
  "Dining/Meeting Table": MdOutlineMeetingRoom,
  "Complimentary Bottled Water": MdOutlineLocalDrink,
  "In-room Safe": FaLock,
  "Iron & Ironing Board": FaTshirt,
  "Walk-in Closet": FaDoorOpen,
  Kitchenette: MdKitchen,
  "Full Kitchen": MdKitchen,
  "Premium Sound System": FaCrown,
  "Home Theatre System": FaCrown,
  "Private Terrace": FaDoorOpen,
  "Spa Bathroom": FaBath,
  "Bathrobes & Slippers": GiSlippers,
  "Complimentary Breakfast Access": MdOutlineFreeBreakfast,
  "Room Service": MdOutlineRoomService,
  "Personal Concierge": FaConciergeBell,
};
